before_script:
  - export LANG=en_US.UTF-8
  - git submodule update --init --recursive
  - rm -rf Gemfile.lock
  - gem install bundler
  - bundle install

production:
  type: build
  script: "bundle exec fastlane staging"
  tags:
    - s4
  only:
    - develop
alpha:
  type: build
  script: "bundle exec fastlane staging"
  tags:
    - s4
  only:
    - /^staging-.*$/
testflight:
  type: build
  script: "bundle exec fastlane testflight"
  tags:
    - artifacts
  only:
    - /^testflight-.*$/ # any git refs (e.g. tag) starting with "appstore-"