before_script:
  - export LANG=en_US.UTF-8
  - brew update
  - brew outdated carthage || brew upgrade carthage

  # download and load envs
  - python tools/download.py --token ${AUTO_CLOSE_TOKEN} --key-version agxzfmF1dG8tY2xvc2VyGAsSC1Byb2plY3RLZXlzGICAgJCo7pAJDA
  
  # install submodules
  - git submodule update --init --recursive

  # update gems & bundle
  - gem install bundler
  - gem outdated
  - gem update
  - bundle install

production:
  type: build
  script: "bundle exec fastlane ios production --env production"
  tags:
    - s4
  only:
    - develop
    - /^production-.*$/
alpha:
  type: build
  script: "bundle exec fastlane ios stage --env staging"
  tags:
    - s4
  except:
    - /^local-.*$/ # any git refs (e.g. tag) starting with "appstore-"
    - /^translations-.*$/ # any git refs (e.g. tag) starting with "appstore-"
    - /^testflight-.*$/ # any git refs (e.g. tag) starting with "appstore-"
local:
  type: build
  script: "bundle exec fastlane ios local --env local"
  tags:
    - s4
  except:
    - /^translations-.*$/ # any git refs (e.g. tag) starting with "appstore-"
    - /^testflight-.*$/ # any git refs (e.g. tag) starting with "appstore-"
testflight:
  type: build
  script: "bundle exec fastlane ios testflight --env production"
  tags:
    - artifacts
  only:
    - /^testflight-.*$/ # any git refs (e.g. tag) starting with "appstore-"
translations:
  type: build
  script: "bundle exec fastlane ios localizations"
  tags:
    - artifacts
  only:
    - develop
    - /^translations-.*$/
  