before_script:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - export LANG=en_US.UTF-8
  - git submodule update --init --recursive
  - rm -rf Gemfile.lock
  - gem install bundler
  - bundle install
  - carthage build --platform ios --no-skip-current

production:
  type: build
  script: "bundle exec fastlane production"
  tags:
    - s4
  only:
    - develop
alpha:
  type: build
  script: "bundle exec fastlane staging"
  tags:
    - s4
  except:
    - /^local-.*$/ # any git refs (e.g. tag) starting with "appstore-"
    - /^translations-.*$/ # any git refs (e.g. tag) starting with "appstore-"
    - /^testflight-.*$/ # any git refs (e.g. tag) starting with "appstore-"
local:
  type: build
  script: "bundle exec fastlane local"
  tags:
    - s4
  except:
    - /^translations-.*$/ # any git refs (e.g. tag) starting with "appstore-"
    - /^testflight-.*$/ # any git refs (e.g. tag) starting with "appstore-"
testflight:
  type: build
  script: "bundle exec fastlane testflight"
  tags:
    - artifacts
  only:
    - /^testflight-.*$/ # any git refs (e.g. tag) starting with "appstore-"
translations:
  type: build
  script: "bundle exec fastlane localizations"
  tags:
    - artifacts
  only:
    - develop
    - /^translations-.*$/
  