osx_image: xcode7.3
language: objective-c
podfile: Example/Podfile
xcode_workspace: Example/AmazonS3RequestManager.xcworkspace

matrix:
    include:
        - xcode_sdk: iphonesimulator9.2
          xcode_scheme: "iOS"
        - xcode_sdk: macosx10.11
          xcode_scheme: "OSX"
