# Reference: https://github.com/pinterest/PINRemoteImage/blob/master/.travis.yml
#            https://github.com/Alamofire/Alamofire/blob/master/.travis.yml
language: objective-c
osx_image: xcode7.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
  - SCHEME="GoogleMapsDirections iOS" SDK=iphonesimulator9.2
  - SCHEME="GoogleMapsDirections OSX" SDK=macosx10.11
  - SCHEME="GoogleMapsDirections tvOS" SDK=appletvsimulator9.1
  - SCHEME="GoogleMapsDirections watchOS" SDK=watchsimulator2.1
  - SCHEME="GooglePlaces iOS" SDK=iphonesimulator9.2
  - SCHEME="GooglePlaces OSX" SDK=macosx10.11
  - SCHEME="GooglePlaces tvOS" SDK=appletvsimulator9.1
  - SCHEME="GooglePlaces watchOS" SDK=watchsimulator2.1

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild -version
  - xctool -workspace GoogleMaps.xcworkspace -scheme "$SCHEME" -sdk "$SDK" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
