osx_image: xcode7.1
language: objective-c

env:
  global:
    - LANG=en_US.UTF-8

cache:
  - bundler

before_install:
  - brew update
  - brew install carthage
  - carthage bootstrap
  
script:
  - rake test
